-- Schema initialization for HiiiWAV budgeting platform
-- Generated by AI to match specification

create extension if not exists "pgcrypto" with schema public;

create table if not exists programs (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  created_at timestamptz default now()
);

create table if not exists years (
  year int primary key check (year between 2020 and 2100)
);

create table if not exists budgets (
  id uuid primary key default gen_random_uuid(),
  program_id uuid not null references programs(id) on delete cascade,
  year int not null references years(year) on delete cascade,
  amount numeric(14,2) not null check (amount >= 0),
  unique (program_id, year)
);

create type if not exists grant_status as enum ('Received','Committed','Pledged','Prospect');
create type if not exists grant_type as enum ('Restricted','Unrestricted');

create table if not exists grants (
  id uuid primary key default gen_random_uuid(),
  code text unique,
  funder text not null,
  status grant_status not null,
  type grant_type not null,
  notes text,
  created_at timestamptz default now()
);

create table if not exists grant_year_amounts (
  id uuid primary key default gen_random_uuid(),
  grant_id uuid not null references grants(id) on delete cascade,
  year int not null references years(year) on delete cascade,
  amount numeric(14,2) not null check (amount >= 0),
  unique (grant_id, year)
);

create table if not exists grant_restrictions (
  id uuid primary key default gen_random_uuid(),
  grant_id uuid not null references grants(id) on delete cascade,
  program_id uuid not null references programs(id) on delete cascade,
  unique (grant_id, program_id)
);

create table if not exists allocation_rules (
  id uuid primary key default gen_random_uuid(),
  grant_id uuid not null references grants(id) on delete cascade,
  year int not null references years(year) on delete cascade,
  program_id uuid not null references programs(id) on delete cascade,
  percent numeric(6,4) not null check (percent >= 0 and percent <= 1),
  unique (grant_id, year, program_id)
);

create or replace function check_allocation_sum() returns trigger as $$
declare
  total numeric(8,4);
begin
  select coalesce(sum(percent),0) into total
  from allocation_rules
  where grant_id = new.grant_id and year = new.year;

  if abs(total - 1.0) > 0.0001 then
    raise exception 'Allocation percents for grant % year % must sum to 1.0', new.grant_id, new.year;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists allocation_sum_ins_upd on allocation_rules;
create trigger allocation_sum_ins_upd
after insert or update on allocation_rules
for each row execute function check_allocation_sum();

create or replace function check_scenario_allocation_sum() returns trigger as $$
declare
  total numeric(8,4);
begin
  select coalesce(sum(percent),0) into total
  from scenario_allocation_rules
  where grant_id = new.grant_id and year = new.year and scenario_id = new.scenario_id;

  if abs(total - 1.0) > 0.0001 then
    raise exception 'Scenario allocation percents for grant % year % must sum to 1.0', new.grant_id, new.year;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists scenario_allocation_sum_ins_upd on scenario_allocation_rules;
create trigger scenario_allocation_sum_ins_upd
after insert or update on scenario_allocation_rules
for each row execute function check_scenario_allocation_sum();

create type if not exists actual_type as enum ('Revenue','Expense');

create table if not exists actuals (
  id uuid primary key default gen_random_uuid(),
  occurred_on date not null,
  program_id uuid not null references programs(id) on delete restrict,
  type actual_type not null,
  amount numeric(14,2) not null check (amount >= 0),
  memo text,
  grant_id uuid references grants(id) on delete set null,
  year int generated always as (extract(year from occurred_on)::int) stored
);

create table if not exists status_probabilities (
  status grant_status primary key,
  probability numeric(4,3) not null check (probability >= 0 and probability <= 1)
);

insert into status_probabilities(status, probability) values
('Received',1.00),('Committed',0.90),('Pledged',0.70),('Prospect',0.30)
on conflict (status) do nothing;

create table if not exists scenarios (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  base_scenario_id uuid references scenarios(id) on delete set null,
  is_live boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists scenarios_live_unique on scenarios(is_live) where is_live;

create table if not exists scenario_budgets (
  id uuid primary key default gen_random_uuid(),
  scenario_id uuid not null references scenarios(id) on delete cascade,
  program_id uuid not null references programs(id) on delete cascade,
  year int not null references years(year) on delete cascade,
  amount numeric(14,2) not null check (amount >= 0),
  unique (scenario_id, program_id, year)
);

create table if not exists scenario_allocation_rules (
  id uuid primary key default gen_random_uuid(),
  scenario_id uuid not null references scenarios(id) on delete cascade,
  grant_id uuid not null references grants(id) on delete cascade,
  year int not null references years(year) on delete cascade,
  program_id uuid not null references programs(id) on delete cascade,
  percent numeric(6,4) not null check (percent >= 0 and percent <= 1),
  unique (scenario_id, grant_id, year, program_id)
);

-- Aggregation views
create or replace view v_allocations as
select
  ar.grant_id,
  ar.year,
  ar.program_id,
  gy.amount as grant_year_amount,
  ar.percent,
  (gy.amount * ar.percent) as allocated_amount
from allocation_rules ar
join grant_year_amounts gy
  on gy.grant_id = ar.grant_id and gy.year = ar.year;

create or replace view v_committed as
select
  va.program_id,
  va.year,
  sum(va.allocated_amount) as committed_amount
from v_allocations va
join grants g on g.id = va.grant_id
where g.status in ('Received','Committed')
group by 1,2;

create or replace view v_weighted_expected as
select
  va.program_id,
  va.year,
  sum(va.allocated_amount * sp.probability) as weighted_expected_amount
from v_allocations va
join grants g on g.id = va.grant_id
join status_probabilities sp on sp.status = g.status
group by 1,2;

create or replace view v_actual_expense as
select program_id, year, sum(case when type='Expense' then amount else 0 end) as actual_spent
from actuals
group by 1,2;

create or replace view v_coverage_summary as
with b as (
  select program_id, year, amount as budget from budgets
)
select
  p.id as program_id,
  p.name as program,
  y.year,
  coalesce(b.budget,0) as budget,
  coalesce(a.actual_spent,0) as actual_spent,
  coalesce(c.committed_amount,0) as committed_funding,
  coalesce(w.weighted_expected_amount,0) as weighted_expected,
  case when coalesce(b.budget,0) = 0 then 0
       else coalesce(c.committed_amount,0) / nullif(b.budget,0) end as coverage_pct,
  greatest(coalesce(b.budget,0) - coalesce(c.committed_amount,0), 0) as gap_to_budget
from years y
cross join programs p
left join b on b.program_id = p.id and b.year = y.year
left join v_actual_expense a on a.program_id = p.id and a.year = y.year
left join v_committed c on c.program_id = p.id and c.year = y.year
left join v_weighted_expected w on w.program_id = p.id and w.year = y.year;

create or replace view v_scenario_allocations as
select
  sar.scenario_id,
  sar.grant_id,
  sar.year,
  sar.program_id,
  gy.amount as grant_year_amount,
  sar.percent,
  (gy.amount * sar.percent) as allocated_amount
from scenario_allocation_rules sar
join grant_year_amounts gy
  on gy.grant_id = sar.grant_id and gy.year = sar.year;

create or replace view v_scenario_committed as
select
  sa.scenario_id,
  sa.program_id,
  sa.year,
  sum(sa.allocated_amount) as committed_amount
from v_scenario_allocations sa
join grants g on g.id = sa.grant_id
where g.status in ('Received','Committed')
group by 1,2,3;

create or replace view v_scenario_weighted_expected as
select
  sa.scenario_id,
  sa.program_id,
  sa.year,
  sum(sa.allocated_amount * sp.probability) as weighted_expected_amount
from v_scenario_allocations sa
join grants g on g.id = sa.grant_id
join status_probabilities sp on sp.status = g.status
group by 1,2,3;

create or replace view v_scenario_coverage_summary as
select
  s.id as scenario_id,
  s.name,
  p.id as program_id,
  p.name as program,
  y.year,
  coalesce(sb.amount, 0) as budget,
  coalesce(a.actual_spent, 0) as actual_spent,
  coalesce(sc.committed_amount, 0) as committed_funding,
  coalesce(sw.weighted_expected_amount, 0) as weighted_expected,
  case when coalesce(sb.amount, 0) = 0 then 0
       else coalesce(sc.committed_amount, 0) / nullif(sb.amount, 0) end as coverage_pct,
  greatest(coalesce(sb.amount, 0) - coalesce(sc.committed_amount, 0), 0) as gap_to_budget
from scenarios s
cross join programs p
cross join years y
left join scenario_budgets sb on sb.scenario_id = s.id and sb.program_id = p.id and sb.year = y.year
left join v_actual_expense a on a.program_id = p.id and a.year = y.year
left join v_scenario_committed sc on sc.scenario_id = s.id and sc.program_id = p.id and sc.year = y.year
left join v_scenario_weighted_expected sw on sw.scenario_id = s.id and sw.program_id = p.id and sw.year = y.year;

create or replace function clone_scenario_data(source_id uuid, target_id uuid)
returns void as $$
begin
  insert into scenario_budgets(scenario_id, program_id, year, amount)
  select target_id, program_id, year, amount
  from scenario_budgets
  where scenario_id = source_id
  on conflict (scenario_id, program_id, year) do update set amount = excluded.amount;

  insert into scenario_allocation_rules(scenario_id, grant_id, year, program_id, percent)
  select target_id, grant_id, year, program_id, percent
  from scenario_allocation_rules
  where scenario_id = source_id
  on conflict (scenario_id, grant_id, year, program_id) do update set percent = excluded.percent;
end;
$$ language plpgsql security definer;

create or replace function apply_scenario_to_live(scenario_id uuid)
returns void as $$
declare
  live_id uuid;
begin
  select id into live_id from scenarios where is_live limit 1;

  if live_id is null then
    insert into scenarios(name, is_live) values ('Live', true) returning id into live_id;
  end if;

  perform clone_scenario_data(scenario_id, live_id);

  delete from budgets;
  insert into budgets(program_id, year, amount)
  select program_id, year, amount
  from scenario_budgets
  where scenario_id = live_id
  on conflict (program_id, year) do update set amount = excluded.amount;

  delete from allocation_rules;
  insert into allocation_rules(grant_id, year, program_id, percent)
  select grant_id, year, program_id, percent
  from scenario_allocation_rules
  where scenario_id = live_id
  on conflict (grant_id, year, program_id) do update set percent = excluded.percent;
end;
$$ language plpgsql security definer;

-- Enable RLS and policies
alter table programs enable row level security;
alter table years enable row level security;
alter table budgets enable row level security;
alter table grants enable row level security;
alter table grant_year_amounts enable row level security;
alter table grant_restrictions enable row level security;
alter table allocation_rules enable row level security;
alter table actuals enable row level security;
alter table status_probabilities enable row level security;
alter table scenarios enable row level security;
alter table scenario_budgets enable row level security;
alter table scenario_allocation_rules enable row level security;

create policy if not exists staff_rw_programs on programs
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_years on years
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_budgets on budgets
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_grants on grants
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_grant_year_amounts on grant_year_amounts
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_grant_restrictions on grant_restrictions
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_allocation_rules on allocation_rules
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_actuals on actuals
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_ro_status_probabilities on status_probabilities
for select using (auth.jwt() ->> 'role' in ('staff','donor'));

create policy if not exists staff_rw_scenarios on scenarios
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_scenario_budgets on scenario_budgets
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

create policy if not exists staff_rw_scenario_allocations on scenario_allocation_rules
for all using (auth.jwt() ->> 'role' = 'staff')
with check (auth.jwt() ->> 'role' = 'staff');

-- Donor read policies on views
alter view v_coverage_summary set (security_invoker = true);
alter view v_committed set (security_invoker = true);
alter view v_weighted_expected set (security_invoker = true);

grant select on v_coverage_summary, v_committed, v_weighted_expected to authenticated, anon;
